---
- hosts: default
  name: 'Base ami of this project'
  roles:
    - ../ansible-role/update-package-manager
    - ../ansible-role/install-chrony
    - ../ansible-role/configure-system-parameters
    - ../ansible-role/mount-efs
    - ../ansible-role/clear-default-account