# EFS_ID
# EFS_REIOGN
# EFS_MOUNTED_DIRECTORY
# EFS_MOUNTED_DIRECTORY_OWNER

---
- name: Create the mount directory
  become: yes
  become_user: root
  become_method: sudo
  ansible.builtin.file:
    state: directory
    path: "{{ EFS_MOUNTED_DIRECTORY }}"

- name: Mount up device
  become: yes
  become_user: root
  become_method: sudo
  ansible.posix.mount:
    path: "{{ EFS_MOUNTED_DIRECTORY }}"
    src: "{{ EFS_ID }}.efs.{{ EFS_REIOGN }}.amazonaws.com:/"
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
    state: mounted # It'll be described in fstab

- name: Change the directory owner and group
  become: yes
  become_user: root
  become_method: sudo
  ansible.builtin.file:
    state: directory
    path: "{{ EFS_MOUNTED_DIRECTORY }}"
    owner: "{{ EFS_MOUNTED_DIRECTORY_OWNER }}"
    group: "{{ EFS_MOUNTED_DIRECTORY_OWNER }}"